### ISSUE TITLE
The output MediaType application/json is not supported for class java.lang.String

### ISSUE THREAD

**Issue by jeremyross** [jam01/xtrasonnet#11]
Hi, I'm hoping you can help me understand what I'm doing wrong here:
```java
var transform = """
            {
                name_title: payload.Salutation,
                name_first: payload.FirstName,
                name_last: payload.LastName,
                primary_email: payload.Email
            }
            """;
final Transformer transformer = Transformer.builder(transform)
        .configurePlugins(plugins -> {
            plugins.removeIf(plugin -> plugin instanceof DefaultJavaPlugin);
            plugins.add(0, new DefaultJavaPlugin(jsonMapper));
        })
        .build();

final String result = transformer.transform(Document.of(contact, MediaTypes.APPLICATION_JAVA)).getContent();
```

```
Caused by: java.lang.IllegalArgumentException: The output MediaType application/json is not supported for class java.lang.String
	at io.github.jam01.xtrasonnet.DataFormatService.lambda$mandatoryWrite$0(DataFormatService.java:62)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at io.github.jam01.xtrasonnet.DataFormatService.mandatoryWrite(DataFormatService.java:62)
	at io.github.jam01.xtrasonnet.Transformer.$anonfun$transform$2(Transformer.scala:244)
	at io.github.jam01.xtrasonnet.Transformer$.io$github$jam01$xtrasonnet$Transformer$$handleException(Transformer.scala:36)
	at io.github.jam01.xtrasonnet.Transformer.transform(Transformer.scala:244)
	at io.github.jam01.xtrasonnet.Transformer.transform(Transformer.scala:210)
```

`contact` is a POJO. 

I've also tried this with, but it doesn't seem to help:
```java
final String result = transformer.transform(
        Document.of(contact, MediaTypes.APPLICATION_JAVA),
        new HashMap<>(),
        MediaTypes.APPLICATION_JSON).getContent();
```
Thanks!

**Comment by jeremyross** [comment]
Yep, that worked. Thanks!
